import About from "@/src/components/About";
import Main from "@/src/components/Main";
import Projects from "@/src/components/Projects";
import Skills from "@/src/components/Skills";
import { Inter } from "next/font/google";
import Head from "next/head";
import Contact from "../components/Contact";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Schehat Abdel Kader</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </>
  );
}
